package osotnikov.demowebapp.web.constants;

public enum LifecycleScopeAndConcurrencyExperimentType {
	
	STATEFUL_DEPENDENT_SCOPE_1("STATEFUL_DEPENDENT_SCOPE_1"),
	STATEFUL_DEPENDENT_SCOPE_2("STATEFUL_DEPENDENT_SCOPE_2"),
	STATELESS_DEPENDENT_SCOPE("STATELESS_DEPENDENT_SCOPE"),
	STATELESS_DEPENDENT_SCOPE_READ_LOCK_10_SEC("STATELESS_DEPENDENT_SCOPE_READ_LOCK_10_SEC"),
	STATELESS_DEPENDENT_SCOPE_WRITE_LOCK_10_SEC("STATELESS_DEPENDENT_SCOPE_WRITE_LOCK_10_SEC"),
	STATELESS_DEPENDENT_SCOPE_WRITE_LOCK_INSTANT("STATELESS_DEPENDENT_SCOPE_WRITE_LOCK_INSTANT"),
	STATEFUL_REQ_SCOPE("STATEFUL_REQ_SCOPE"),
	POJO_REQ_SCOPE("POJO_REQ_SCOPE"),
	POJO_DEPENDENT_SCOPE_1("POJO_DEPENDENT_SCOPE_1"),
	POJO_DEPENDENT_SCOPE_2("POJO_DEPENDENT_SCOPE_2");
	
	private String name;
	
	private LifecycleScopeAndConcurrencyExperimentType(String name){
		this.name = name;
	}

	public String getName() {
		return name;
	}
	
}
